import { NextPage } from "next";
import Head from "next/head";
import Navbar from "./Navbar";
import styles from "../../styles/Home.module.css";
import Link from "next/link";

const Layout: NextPage = ({ children }): any => {
  return (
    <div>
      <Head>
        <title>Rakibul Hasan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container">{children}</div>
      <footer className={styles.footer}>
        <Link href="/">
          <a>
            Powered by{" "}
            <span className={styles.logo}>
              <h3>Rakibul Hasan</h3>
            </span>
          </a>
        </Link>
      </footer>
    </div>
  );
};

export default Layout;
